engines:
  rubocop:
    enabled: false
    #checks:
    # Rubocop/Metrics/ClassLength:
    #   enabled: false
  brakeman:
    enabled: true
    checks:
      no_attr_accessible:
        enabled: false
      open_redirect:
        enabled: false
      sql_injection:
        enabled: false
      xss_to_json:
        enabled: false
      mass_assign_call:
        enabled: false
      dangerous_attr_accessible:
        enabled: false
      unsafe_constantize:
        enabled: false
      regex_dos:
        enabled: false
  eslint:
    enabled: false  
  csslint:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - ruby
        #mass_threshold: 30
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"